'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import { useState } from 'react';
import Navbar from "./components/NavBar";

import Sidebar from "./components/Sidebar";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });
console.log(inter)

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const [isSidebarOpen, setIsSidebarOpen] = useState(true);

  const toggleSidebar = () => {
      setIsSidebarOpen(!isSidebarOpen);
  };

  return (
    <html lang="en">
      <body className={inter.className}>
            <Header onToggleSidebar={toggleSidebar} />
              <div className="flex h-full flex">
                <Sidebar isOpen={isSidebarOpen} />
                <div className="basis-10/12">
                  {children}
                </div>
              </div>
    </body>
    </html>
  );
}
